"""
api/routers/meal_logs.py

Meal logging endpoints:
  POST   /meal-logs/              — log a consumed meal
  GET    /meal-logs/              — list meal logs (filterable by date range + slot)
  DELETE /meal-logs/{log_id}      — delete a log entry
  GET    /meal-logs/adherence     — daily calorie adherence for last N days
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from api.dependencies import get_db, get_current_user
from api.schemas.tracking_schemas import (
    LogMealRequest, MealLogResponse, MealLogListResponse,
    DailyAdherenceResponse,
)
from api.services.tracking_service import (
    log_meal, list_meal_logs, delete_meal_log, get_adherence,
)
from db.models import User

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/meal-logs", tags=["Meal Logs"])


# ── POST /meal-logs/ ──────────────────────────────────────────────────────────

@router.post(
    "/",
    response_model=MealLogResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Log a consumed meal",
    description="""
Log a meal you've eaten. This powers the weekly progress report.

**meal_slot** must be one of: `breakfast`, `lunch`, `dinner`, `snack`  
**log_date** must be ISO format: `2026-03-01`  
**source** options: `manual` (typed in), `image` (from photo scan), `plan` (from meal plan)

If this meal matches a recipe generated by the AI, pass `recipe_id` to  
link the log entry to that recipe row in the database.
""",
)
def log_meal_endpoint(
    payload: LogMealRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    try:
        return log_meal(user=current_user, db=db, payload=payload)
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))


# ── GET /meal-logs/ ───────────────────────────────────────────────────────────

@router.get(
    "/",
    response_model=MealLogListResponse,
    summary="List meal logs",
    description="""
Returns your meal history.

**Filter options:**
- `days` — last N days (default: 7). Ignored if `date_from` is provided.
- `date_from` / `date_to` — explicit date range (ISO format).
- `meal_slot` — filter to a specific slot (breakfast / lunch / dinner / snack).
""",
)
def list_logs(
    days:      int            = Query(default=7,    ge=1, le=90,  description="Last N days (default 7)"),
    date_from: Optional[str]  = Query(default=None, description="Start date ISO e.g. 2026-02-01"),
    date_to:   Optional[str]  = Query(default=None, description="End date ISO e.g. 2026-03-01"),
    meal_slot: Optional[str]  = Query(default=None, description="Filter by slot: breakfast/lunch/dinner/snack"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    try:
        return list_meal_logs(
            user_id   = current_user.id,
            db        = db,
            days      = days,
            date_from = date_from,
            date_to   = date_to,
            meal_slot = meal_slot,
        )
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))


# ── GET /meal-logs/adherence ──────────────────────────────────────────────────

@router.get(
    "/adherence",
    response_model=list[DailyAdherenceResponse],
    summary="Get daily calorie adherence",
    description="""
Returns a day-by-day breakdown of how closely you hit your calorie target.

- `days` — how many days back to look (default: 7, max: 30)
- `calorie_target` — override your saved goal target for this calculation

**adherence_pct** = `(actual_calories / planned_calories) × 100`  
100% = perfect. <80% = likely under-eating. >120% = over target.
""",
)
def adherence(
    days:           int           = Query(default=7,  ge=1, le=30),
    calorie_target: Optional[int] = Query(default=None, ge=500, le=5000, description="Override calorie target"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    return get_adherence(
        user_id        = current_user.id,
        db             = db,
        days           = days,
        calorie_target = calorie_target,
    )


# ── DELETE /meal-logs/{log_id} ────────────────────────────────────────────────

@router.delete(
    "/{log_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a meal log entry",
    description="Delete a logged meal. Users can only delete their own log entries.",
)
def delete_log(
    log_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    deleted = delete_meal_log(log_id=log_id, user_id=current_user.id, db=db)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Log entry '{log_id}' not found.",
        )